services:
  postgres:
    image: postgres:16-alpine
    container_name: autospot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: autospot_user
      POSTGRES_PASSWORD: autospot_password
      POSTGRES_DB: autospot_db
    ports:
      - "5433:5432"
    volumes:
      - autospot_postgres_data:/var/lib/postgresql/data

volumes:
  autospot_postgres_data: