"""add avatar storage path to user

Revision ID: 03398aeab48e
Revises: ceb29d9a8396
Create Date: 2026-07-23 20:08:29.416880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03398aeab48e'
down_revision: Union[str, Sequence[str], None] = 'ceb29d9a8396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_storage_path', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_storage_path')
    # ### end Alembic commands ###
