"""add image storage path to post

Revision ID: 5e911496c3c2
Revises: cd7acddd66d0
Create Date: 2026-07-20 20:56:51.948556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e911496c3c2'
down_revision: Union[str, Sequence[str], None] = 'cd7acddd66d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_storage_path', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_storage_path')
    # ### end Alembic commands ###
