"""fix add image storage path to post

Revision ID: ceb29d9a8396
Revises: 5e911496c3c2
Create Date: 2026-07-21 01:29:53.968231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb29d9a8396'
down_revision: Union[str, Sequence[str], None] = '5e911496c3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_storage_path',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'image_storage_path',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
